#!/usr/bin/env python3
"""
Optimiza imágenes de la galería de Fuego Dance:
  - Genera thumbnails WebP (400px) para la grilla
  - Genera versión WebP mediana (1600px) para lightbox
  - APLICA orientación EXIF (corrige fotos verticales volteadas)
  - Mantiene los originales intactos
"""
import os
import sys
from pathlib import Path
from PIL import Image, ImageOps

GALLERY_DIR = Path("/mnt/sda/fuegodance/gallery")
THUMBS_DIR = Path("/mnt/sda/fuegodance/thumbnails")
WEB_DIR = Path("/mnt/sda/fuegodance/web")

QUALITY_HIGH = 85   # Para versiones medianas (lightbox)
QUALITY_LOW = 80    # Para thumbnails (grilla)
THUMB_SIZE = 400    # px ancho máximo
WEB_SIZE = 1600     # px ancho máximo para lightbox


def ensure_dirs():
    THUMBS_DIR.mkdir(parents=True, exist_ok=True)
    WEB_DIR.mkdir(parents=True, exist_ok=True)


def get_image_files():
    """Retorna lista de archivos de imagen en el directorio de galería."""
    extensions = {'.jpg', '.jpeg', '.png', '.gif', '.webp'}
    files = sorted(
        f for f in GALLERY_DIR.iterdir()
        if f.suffix.lower() in extensions and f.is_file()
    )
    return files


def needs_update(src: Path, dest: Path) -> bool:
    """True si necesita regenerarse: no existe o el source es más nuevo."""
    if not dest.exists():
        return True
    return src.stat().st_mtime > dest.stat().st_mtime


def optimize_image(src: Path):
    """
    Genera thumbnail + versión web mediana para una imagen.
    Usa Pillow para aplicar EXIF orientation automáticamente.
    """
    basename = src.stem
    thumb_path = THUMBS_DIR / f"{basename}.webp"
    web_path = WEB_DIR / f"{basename}.webp"

    results = {}

    try:
        img = Image.open(src)
        # Aplica orientación EXIF (corrige rotación vertical)
        img = ImageOps.exif_transpose(img)
        if img is None:
            return {"error": "exif_transpose returned None"}
        original_mode = img.mode

        # --- Thumbnail (400px) ---
        if needs_update(src, thumb_path) or needs_exif_fix(src, thumb_path):
            thumb = img.copy()
            thumb.thumbnail((THUMB_SIZE, THUMB_SIZE), Image.LANCZOS)
            if original_mode == 'RGBA':
                thumb = thumb.convert('RGB')
            thumb.save(thumb_path, 'WEBP', quality=QUALITY_LOW)
            size_kb = thumb_path.stat().st_size / 1024
            results["thumbnail"] = f"{size_kb:.0f} KB"
        else:
            size_kb = thumb_path.stat().st_size / 1024
            results["thumbnail"] = f"{size_kb:.0f} KB (cached)"

        # --- Versión web mediana (1600px) ---
        if needs_update(src, web_path) or needs_exif_fix(src, web_path):
            web = img.copy()
            web.thumbnail((WEB_SIZE, WEB_SIZE), Image.LANCZOS)
            if original_mode == 'RGBA':
                web = web.convert('RGB')
            web.save(web_path, 'WEBP', quality=QUALITY_HIGH)
            size_kb = web_path.stat().st_size / 1024
            results["web"] = f"{size_kb:.0f} KB"
        else:
            size_kb = web_path.stat().st_size / 1024
            results["web"] = f"{size_kb:.0f} KB (cached)"

    except Exception as e:
        results["error"] = str(e)

    return results


def needs_exif_fix(src: Path, dest: Path) -> bool:
    """Check if the source has EXIF orientation and the dest was generated by old cwebp."""
    if not dest.exists():
        return True
    try:
        img = Image.open(src)
        exif = img.getexif()
        orient = exif.get(0x0112, 1)
        return orient != 1  # Needs rotation
    except Exception:
        return False


def main():
    ensure_dirs()
    files = get_image_files()

    if not files:
        print("❌ No se encontraron imágenes en", GALLERY_DIR)
        sys.exit(1)

    print(f"📸 Optimizando {len(files)} imágenes (con corrección EXIF)...")
    print(f"   Originales:  {GALLERY_DIR}")
    print(f"   Thumbnails:  {THUMBS_DIR} ({THUMB_SIZE}px WebP)")
    print(f"   Web:         {WEB_DIR} ({WEB_SIZE}px WebP)")
    print()

    total_original = 0
    total_thumb = 0
    total_web = 0
    errors = 0
    exif_fixed = 0

    for i, src in enumerate(files, 1):
        orig_size = src.stat().st_size
        total_original += orig_size
        orig_kb = orig_size / 1024

        # Check if it has EXIF orientation
        has_exif = False
        orient = 1
        try:
            img_tmp = Image.open(src)
            exif = img_tmp.getexif()
            orient = exif.get(0x0112, 1)
            has_exif = orient != 1
            img_tmp.close()
        except Exception:
            pass

        if has_exif:
            print(f"  [{i:2d}/{len(files)}] 🔄 {src.name} ({orig_kb:.0f} KB) [EXIF:{orient}]")
        else:
            print(f"  [{i:2d}/{len(files)}] {src.name} ({orig_kb:.0f} KB)")

        result = optimize_image(src)

        thumb_size = THUMBS_DIR / f"{src.stem}.webp"
        web_size = WEB_DIR / f"{src.stem}.webp"

        if thumb_size.exists():
            total_thumb += thumb_size.stat().st_size
        if web_size.exists():
            total_web += web_size.stat().st_size

        if "error" in result:
            errors += 1
            print(f"         ↳ ERROR: {result['error']}")
            continue

        if has_exif:
            exif_fixed += 1

        thumb_str = result.get("thumbnail", "?")
        web_str = result.get("web", "?")
        print(f"         ↳ thumb: {thumb_str} | web: {web_str}")

    # Resumen final
    mb_orig = total_original / (1024 * 1024)
    mb_thumb = total_thumb / (1024 * 1024)
    mb_web = total_web / (1024 * 1024)
    mb_total_opt = mb_thumb + mb_web

    print()
    print("=" * 55)
    print(f"  📊 RESUMEN FINAL")
    print("=" * 55)
    print(f"  Originales:           {mb_orig:.1f} MB")
    print(f"  Thumbnails (400px):    {mb_thumb:.1f} MB")
    print(f"  Web (1600px):         {mb_web:.1f} MB")
    print(f"  Total optimizado:     {mb_total_opt:.1f} MB")
    print(f"  Ahorro en disco:      {mb_orig - mb_total_opt:.1f} MB ({100 - (mb_total_opt/mb_orig*100):.0f}%)")
    print(f"  🔄 EXIF corregidas:   {exif_fixed}")
    if errors:
        print(f"  ⚠️  Errores: {errors}")
    else:
        print(f"  ✅ Sin errores")
    print("=" * 55)


if __name__ == "__main__":
    main()
